import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import { signupSchema } from '@/lib/security';
import bcrypt from 'bcryptjs';

// Rate limiting - simple in-memory storage
const signupAttempts = new Map<string, { count: number; resetTime: number }>();

function checkRateLimit(ip: string): boolean {
  const now = Date.now();
  const attempts = signupAttempts.get(ip);
  
  if (!attempts || now > attempts.resetTime) {
    signupAttempts.set(ip, { count: 1, resetTime: now + 10 * 60 * 1000 }); // 10 minutes
    return true;
  }
  
  if (attempts.count >= 3) {
    return false; // Block after 3 attempts
  }
  
  attempts.count++;
  return true;
}

export async function POST(request: NextRequest) {
  try {
    // Rate limiting
    const clientIp = request.ip || request.headers.get('x-forwarded-for') || 'unknown';
    if (!checkRateLimit(clientIp)) {
      return NextResponse.json(
        { error: 'Too many signup attempts. Please try again in 10 minutes.' },
        { status: 429 }
      );
    }

    const body = await request.json();

    // Validate input with Zod
    const validation = signupSchema.safeParse(body);
    if (!validation.success) {
      return NextResponse.json(
        { error: validation.error.errors[0].message },
        { status: 400 }
      );
    }

    const { name, email, password, phone } = validation.data;

    // Check if user already exists with this email
    const existingUserByEmail = await prisma.user.findUnique({
      where: { email: email.toLowerCase() },
    });

    if (existingUserByEmail) {
      return NextResponse.json(
        { error: 'An account with this email already exists' },
        { status: 409 }
      );
    }

    // Check if there's an existing user with the same phone number
    const existingUserByPhone = await prisma.user.findFirst({
      where: { phone },
    });

    let user;
    let isUpgrade = false;

    // If there's an existing user with this phone number
    if (existingUserByPhone) {
      // Check if it's an admin-created account (no real email, just the auto-generated one)
      const isAutoGeneratedEmail = existingUserByPhone.email.includes('@vetclinic.local');
      
      if (isAutoGeneratedEmail) {
        // This is an admin-only account - upgrade it!
        const hashedPassword = await bcrypt.hash(password, 12);
        
        user = await prisma.user.update({
          where: { id: existingUserByPhone.id },
          data: {
            email: email.toLowerCase(),
            password: hashedPassword,
            name: name || existingUserByPhone.name, // Use provided name or keep existing
            governorate: existingUserByPhone.governorate,
            area: existingUserByPhone.area,
            address: existingUserByPhone.address,
          },
          select: {
            id: true,
            email: true,
            name: true,
            phone: true,
            governorate: true,
            area: true,
            address: true,
            role: true,
            createdAt: true,
          },
        });
        isUpgrade = true;
      } else {
        // User with this phone number has a real email already
        return NextResponse.json(
          { error: 'An account with this phone number already exists. Please log in instead.' },
          { status: 409 }
        );
      }
    } else {
      // No existing user with this phone - create a new account
      const hashedPassword = await bcrypt.hash(password, 12);
      
      user = await prisma.user.create({
        data: {
          email: email.toLowerCase(),
          password: hashedPassword,
          name,
          phone,
          role: 'user', // Regular user (not admin)
        },
        select: {
          id: true,
          email: true,
          name: true,
          phone: true,
          governorate: true,
          area: true,
          address: true,
          role: true,
          createdAt: true,
        },
      });
    }

    // Clear signup attempts on success
    signupAttempts.delete(clientIp);

    // Return success
    return NextResponse.json({
      success: true,
      message: isUpgrade 
        ? 'Your account has been upgraded! You can now log in with your email and password.'
        : 'Account created successfully!',
      isUpgrade,
      user: {
        id: user.id,
        email: user.email,
        name: user.name,
        phone: user.phone,
        governorate: user.governorate,
        area: user.area,
        address: user.address,
        role: user.role,
      },
    }, { status: 201 });
  } catch (error) {
    console.error('Signup error:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}
